language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
install:
  - composer install
matrix:
  allow_failures:
    - php: hhvm
  include:
    - php: 5.3
      dist: precise
script:
 - mkdir -p build/logs
 - phpunit --coverage-clover build/logs/clover.xml
after_script:
 - php vendor/bin/coveralls -v
